name: Mobile Dev Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      app: app/build/outputs/apk/debug
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug
  upload-to-mobile-dev:
    needs: build
    name: Run Flows on Maestro Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  
      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: app/build/outputs/app-debug.apk
          workspace: .github/
      # - uses: mobile-dev-inc/action-maestro-cloud@v1.1.1
      #   with:
      #     api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
      #     app-file: app/build/outputs/apk/release/app-release.apk
      #     mapping-file: app/build/outputs/mapping/release/mapping.txt
